# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

# VM 1 Gateway
  config.vm.box = "ubuntu/focal64" # definindo o SO da VM
  
  config.vm.provider "virtualbox" do |vb| # definindo as configs de capacidade da VM
    vb.memory =  1024
    vb.cpus = 1
  end
  config.vm.define "gateway-vm" do |gateway|
    
    gateway.vm.network "private_network", ip: "192.168.56.254" # definindo ip e a rede da VM
    
    gateway.vm.network "public_network", type: "dhcp", bridge: "wlp0s20f3" # definindo a rede publica da VM
    
    gateway.vm.synced_folder "/home/matheus/VM_Vagrant/Trabalho_Vagrant/vm_cfg", "/vagrant_shared" # compartilhando a pasta do projeto com a VM

    gateway.vm.provision "shell", path: "/home/matheus/VM_Vagrant/Trabalho_Vagrant/vm_cfg/cfg_vm1.sh" # executando o script de configuração da VM

    gateway.vm.hostname = "gw" # definindo o hostname da VM
  end
      
# VM 2 Servidor Web
  config.vm.box = "ubuntu/focal64"
      
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
    
  config.vm.define "servidor-web-vm" do |web| 
    
    web.vm.network "private_network", ip: "192.168.56.15" 
  
    web.vm.synced_folder "/home/matheus/VM_Vagrant/Trabalho_Vagrant", "/var/www/html" 

    web.vm.synced_folder "/home/matheus/VM_Vagrant/Trabalho_Vagrant/vm_cfg", "/vagrant_shared" 
  
    web.vm.network "forwarded_port", guest: 81, host: 8080 # definindo a porta de acesso a VM

    web.vm.provision "shell", path: "/home/matheus/VM_Vagrant/Trabalho_Vagrant/vm_cfg/cfg_vm2.sh" 

    web.vm.hostname = "servidor-web"
  end

# VM 3 Servidor BD
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
  end
    
  config.vm.define "servidor-bd-vm" do |banco|

    banco.vm.network "private_network", ip: "192.168.56.16"
    
    banco.vm.synced_folder "/home/matheus/VM_Vagrant/Trabalho_Vagrant/vm_cfg", "/vagrant_shared"
  
    banco.vm.network "forwarded_port", guest: 81, host: 8081

    banco.vm.provision "shell", path: "/home/matheus/VM_Vagrant/Trabalho_Vagrant/vm_cfg/cfg_vm3.sh"

    banco.vm.hostname = "servidor-BD"
  end
end
